- hosts: centos
  tasks:
    - name: install python-docker centos
      yum:
        name: python-docker
        state: present
    - name: pull image 
      docker_image:
        name: harrysus02/apache-jenkins:latest
        pull: yes
        rm: yes
    - name: create container
      docker_container:
        name: container_by_jenkins
        image: harrysus02/apache-jenkins:latest
        state: started
        published_ports:
          - 83:80
        recreate: yes
        interactive: yes
        detach: yes
